version: "3.8"
services:
  backend:
    build:
      context: https://github.com/HongyuYang296/openAgent-nodeTs.git
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: https://github.com/HongyuYang296/openAgent-react.git
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
